### ISSUE TITLE
Probleme mit dem Pick and Ban Tool SCN Caster Sujuki

### ISSUE THREAD

**Issue by Sujuki2000** [FearNixx/vigilant-bans#1] opened 2021-03-05 11:25 UTC
![Screenshot (17)](https://user-images.githubusercontent.com/80101760/110109509-dae22500-7dad-11eb-829e-4e81cd4a4534.png)
![Screenshot (18)](https://user-images.githubusercontent.com/80101760/110109510-db7abb80-7dad-11eb-9f15-b42cc5082453.png)
![Screenshot (19)](https://user-images.githubusercontent.com/80101760/110109512-db7abb80-7dad-11eb-8703-4ad10d5700d6.png)

**Comment by MarkTwoFive** [comment] 2021-03-06 17:36
Since the issue was not described very much, I needed some tome to reproduce this. However, I was able to and released [version 1.0.1](https://github.com/FearNixx/vigilant-bans/releases/tag/v1.0.1) that includes a work-around for this.  

The underlying cause is an update of DefinitelyTyped/DefinitelyTyped that caused [several issues](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44946).  
In our case, the patch increment wasn't semver-compliant and introduced breaking changes to the type definitions. That's why the compile failed when the application was started. The work-around for us is just pinning ``@types/fs-extra`` to ``9.0.0`` which doesn't have this issue.

I'm leaving this open until the actual issue is resolved and the work-around removed.

**Comment by MarkTwoFive** [comment] 2022-02-03 19:18
Since this has been resolved upstream, I'll close this issue.

**Closed as completed by MarkTwoFive** 2022-02-03 19:18 UTC
